name: GitHub-Profile-3D-Contrib

on:
  schedule: # Roda a cada 24 horas
    - cron: "0 0 * * *"
  workflow_dispatch:

# Permissão para que a Action possa fazer o commit e push do arquivo gerado
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v5
      
      # Passo que gera a imagem 3D, usando ENV
      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.PAT}
          USERNAME: ${{ github.repository_owner }}
          
      # Passo que faz o commit e push do arquivo gerado para o seu repositório
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "generated"
            git push
          fi